### ISSUE TITLE
buck build failed: java-related issue

### ISSUE THREAD

**Issue by artagnon** [facebook/homebrew-fb#1]
```
artagnon|master=:~/src/rhine$ brew install --HEAD buck
==> Installing buck from facebook/homebrew-fb
==> Cloning https://github.com/facebook/buck.git
Updating /Library/Caches/Homebrew/buck--git
==> Checking out branch master
==> ant
==> ./bin/buck build buck
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

[-] BUILDING...FINISHED 3.9s
```

I even installed Java for OSX. What am I missing?

**Comment by Coneko** [comment]
I think the output is truncated by brew, there should be more information about the build failure in `~/Library/Logs/Homebrew/`.

**Comment by artagnon** [comment]
Ah, my $ANDROID_SDK was pointing to an invalid location (remnant of some past Android hacking in my ~/.zshrc). Unsetting it fixes the build. Thanks.

**Comment by Coneko** [comment]
No problem, happy to help.
